*********** Korea's MicroData Analytics in 2021-4 
*** written by Jisun Baek 

*** This file provides english version of variable labels for KHIES 2012-2013 

        label variable v1 "survey year 조사년도"
        label variable v2 "survey month/quarter 조사월(분기)"
        label variable v3 "hhid 가구일련번호"
        label variable v4 "가구구분"
        label variable v5 "# of hh members 가구원수"
        label variable v6 "취업인원수"
        label variable v7 "노인가구"
        label variable v8 "모자가구"
        label variable v9 "맞벌이가구"
        label variable v10 "일반가구"
        label variable v11 "세대구분"
        label variable v12 "1-2 have spouse 3 no spouse 배우자유무"
        label variable v13 "hh 1 head 가구주_가구주와의관계"
        label variable v14 "hh sex 1 male 2 female 가구주-성별"
        label variable v15 "hh age 가구주-연령"
        label variable v16 "hh edu 0 no edu 1 elem 2 mid 3 high 4 somecol 5 col 6-7 gradsch 가구주_학력"
        label variable v17 "hh edustat 1 graduated 2 enrolled 3 dropped 4 on leave 가구주_수학여부"
        label variable v18 "hh Iemp 1 employeed 2 not employeed 가구주_취업여부"
        label variable v19 "hh industry 가구주_산업코드"
        label variable v20 "hh occupation 가구주_직업코드"
        label variable v21 "hh empstat 1 fulltime 2 parttime 3 dayworker 4 employer 5 self-employeed 6 unpaid family 7 other 가구주_종사상지위"
        label variable v22 "hm2 relationship to hh 가구원2_가구주와의관계"
        label variable v23 "hm2 sex 가구원2_성별"
        label variable v24 "hm2 age 가구원2_연령"
        label variable v25 "hm2 edu 가구원2_학력"
        label variable v26 "hm2 edustat 가구원2_수학여부"
        label variable v27 "hm2 Iemp 가구원2_취업여부"
        label variable v28 "hm2 industry 가구원2_산업"
        label variable v29 "hm2 occupation 가구원2_직업"
        label variable v30 "hm2 empstat 가구원2_종사상지위"
        label variable v31 "hm3 relationship to hh 가구원3_가구주와의관계"
        label variable v32 "hm3 sex 가구원3_성별"
        label variable v33 "hm3 age 가구원3_연령"
        label variable v34 "hm3 edu 가구원3_학력"
        label variable v35 "hm3 edustat 가구원3_수학여부"
        label variable v36 "hm3 Iemp 가구원3_취업여부"
        label variable v37 "hm3 industry 가구원3_산업"
        label variable v38 "hm3 occupation 가구원3_직업"
        label variable v39 "hm3 empstat 가구원3_종사상지위"
        label variable v40 "hm4 rel. to hh 가구원4_가구주와의관계"
        label variable v41 "hm4 sex 가구원4_성별"
        label variable v42 "hm4 age 가구원4_연령"
        label variable v43 "hm4 edu 가구원4_학력"
        label variable v44 "hm4 edustat 가구원4_수학여부"
        label variable v45 "hm4 Iemp 가구원4_취업여부"
        label variable v46 "hm4 industry 가구원4_산업"
        label variable v47 "hm4 occupation 가구원4_직업"
        label variable v48 "hm4 empstat 가구원4_종사상지위"
        label variable v49 "hm5 rel. to hh 가구원5_가구주와의관계"
        label variable v50 "hm5 sex 가구원5_성별"
        label variable v51 "hm5 age 가구원5_연령"
        label variable v52 "hm5 edu 가구원5_학력"
        label variable v53 "hm5 edustat 가구원5_수학여부"
        label variable v54 "hm5 Iemp 가구원5_취업여부"
        label variable v55 "hm5 industry 가구원5_산업"
        label variable v56 "hm5 occupation 가구원5_직업"
        label variable v57 "hm5 empstat 가구원5_종사상지위"
        label variable v58 "hm6 rel. to hh 가구원6_가구주와의관계"
        label variable v59 "hm6 sex 가구원6_성별"
        label variable v60 "hm6 age 가구원6_연령"
        label variable v61 "hm6 edu 가구원6_학력"
        label variable v62 "hm6 edustat 가구원6_수학여부"
        label variable v63 "hm6 Iemp 가구원6_취업여부"
        label variable v64 "hm6 industry 가구원6_산업"
        label variable v65 "hm6 occupation 가구원6_직업"
        label variable v66 "hm6 empstat 가구원6_종사상지위"
        label variable v67 "hm7 rel. to hh 가구원7_가구주와의관계"
        label variable v68 "hm7 sex 가구원7_성별"
        label variable v69 "hm7 age 가구원7_연령"
        label variable v70 "hm7 edu 가구원7_학력"
        label variable v71 "hm7 edustat 가구원7_수학여부"
        label variable v72 "hm7 Iemp 가구원7_취업여부"
        label variable v73 "hm7 industry 가구원7_산업"
        label variable v74 "hm7 occupation 가구원7_직업"
        label variable v75 "hm7 empstat 가구원7_종사상지위"
        label variable v76 "hm8 rel. to hh 가구원8_가구주와의관계"
        label variable v77 "hm8 sex 가구원8_성별"
        label variable v78 "hm8 age 가구원8_연령"
        label variable v79 "hm8 edu 가구원8_학력"
        label variable v80 "hm8 edustat 가구원8_수학여부"
        label variable v81 "hm8 Iemp 가구원8_취업여부"
        label variable v82 "hm8 industry 가구원8_산업"
        label variable v83 "hm8 occupation 가구원8_직업"
        label variable v84 "hm8 empstat 가구원8_종사상지위"
        label variable v85 "취업배우자"
        label variable v86 "학업배우자"
        label variable v87 "기타배우자"
        label variable v88 "취업자녀"
        label variable v89 "학업자녀"
        label variable v90 "기타자녀"
        label variable v91 "거처구분"
        label variable v92 "# cars owned 자동차소유대수(휘발유+경우+LPG)"
        label variable v93 "whether living in the place owned by the household 1 owned 입주형태"
        label variable v94 "월세평가액"
        label variable v95 "전세보증금"
        label variable v96 "월세(사글세)"
        label variable v97 "사용면적"
        label variable v98 "1 own houses 2 not own any 주택소유구분"
        label variable v99 "가중치(weight)"
        label variable v100 "income 소득"
        label variable v101 "current income 경상소득"
        label variable v102 "earned income 근로소득"
        label variable v103 "hh earned income 가구주소득"
        label variable v104 "spouse earned income 배우자소득"
        label variable v105 "other hh member's earned income 기타가구원소득"
        label variable v106 "business income 사업소득"
        label variable v107 "hh business income 가구주사업소득"
        label variable v108 "spouse business income 배우자사업소득"
        label variable v109 "other hh member's business income 기타가구원사업소득"
        label variable v110 "rental income 주택등임대소득"
        label variable v111 "property income 재산소득"
        label variable v112 "interest income 이자소득"
        label variable v113 "dividend income 배당소득"

        label variable v116 "기타재산소득"
        label variable v117 "transfer income 이전소득"
        label variable v118 "public pension 공적연금"
        label variable v119 "basic old age pension 기초노령연금"
        label variable v120 "social security benefits 사회수혜금"
        label variable v121 "사회적현물이전"
        label variable v122 "세금환급금"
        label variable v123 "transfers between households 가구간이전"
        label variable v124 "할인혜택"
        label variable v125 "other transfer income 기타이전소득"
        label variable v126 "비경상소득"
        label variable v127 "경조소득"
        label variable v128 "퇴직금및연금일시금"
        label variable v129 "기타비경상소득"
        label variable v130 "기타수입"
        label variable v131 "자산변동으로인한수입"
        label variable v132 "부채증가로인한수입"
        label variable v133 "자산이전으로인한수입"
        label variable v134 "가계지출"
        label variable v135 "소비지출"
        label variable v136 "01.식료품및비주류음료"
        label variable v137 "곡물"
        label variable v138 "곡물가공품"
        label variable v139 "빵및떡류"
        label variable v140 "육류"
        label variable v141 "육류가공품"
        label variable v142 "신선수산동물"
        label variable v143 "염건수산동물"
        label variable v144 "기타수산동물가공"
        label variable v145 "유제품및알"
        label variable v146 "유지류"
        label variable v147 "과일및과일가공품"
        label variable v148 "채소및채소가공품"
        label variable v149 "해조및해조가공품"
        label variable v150 "당류및과자류"
        label variable v151 "조미식품"
        label variable v152 "기타식품"
        label variable v153 "커피및차"
        label variable v154 "쥬스및기타음료"
        label variable v155 "02.주류및담배"
        label variable v156 "주류"
        label variable v157 "담배"
        label variable v158 "03.의류및신발"
        label variable v159 "직물및외의"
        label variable v160 "내의"
        label variable v161 "기타의복"
        label variable v162 "의복관련서비스"
        label variable v163 "신발"
        label variable v164 "신발서비스"
        label variable v165 "04.주거및수도광열"
        label variable v166 "실제주거비"
        label variable v167 "주택유지및수선"
        label variable v168 "상하수도및폐기물처리"
        label variable v169 "기타주거관련서비스"
        label variable v170 "연료비"
        label variable v171 "05.가정용품및가사서비스"
        label variable v172 "가구및조명"
        label variable v173 "실내장식"
        label variable v174 "가구·조명및장식서비스"
        label variable v175 "가정용섬유"
        label variable v176 "가전및가정용기기"
        label variable v177 "가전관련서비스"
        label variable v178 "가사용품"
        label variable v179 "가정용공구및기타"
        label variable v180 "가사소모품"
        label variable v181 "가사서비스"
        label variable v182 "06.보건"
        label variable v183 "의약품"
        label variable v184 "의료용소모품"
        label variable v185 "보건의료용품및기구"
        label variable v186 "외래의료서비스"
        label variable v187 "치과서비스"
        label variable v188 "기타의료서비스"
        label variable v189 "입원서비스"
        label variable v190 "07.교통"
        label variable v191 "자동차구입"
        label variable v192 "기타운송기구구입"
        label variable v193 "운송기구유지및수리"
        label variable v194 "운송기구연료비"
        label variable v195 "기타개인교통서비스"
        label variable v196 "철도운송"
        label variable v197 "육상운송"
        label variable v198 "기타운송"
        label variable v199 "기타교통관련서비스"
        label variable v200 "08.통신"
        label variable v201 "우편서비스"
        label variable v202 "통신장비"
        label variable v203 "통신서비스"
        label variable v204 "09.오락·문화"
        label variable v205 "영상음향기기"
        label variable v206 "사진광학장비"
        label variable v207 "정보처리장치"
        label variable v208 "기록매체"
        label variable v209 "영상음향및정보기기수리"
        label variable v210 "오락문화내구재"
        label variable v211 "악기기구"
        label variable v212 "오락문화내구재유지및수리"
        label variable v213 "장난감및취미용품"
        label variable v214 "캠핑및운동관련용품"
        label variable v215 "화훼관련용품"
        label variable v216 "애완동물관련물품"
        label variable v217 "화훼및애완동물서비스"
        label variable v218 "운동및오락서비스"
        label variable v219 "문화서비스"
        label variable v220 "복권"
        label variable v221 "서적"
        label variable v222 "기타인쇄물"
        label variable v223 "문구"
        label variable v224 "단체여행비"
        label variable v225 "10.교육"
        label variable v226 "정규교육"
        label variable v227 "초등교육"
        label variable v228 "중등교육"
        label variable v229 "고등교육"
        label variable v230 "학원및보습교육"
        label variable v231 "학원및보습교육(성인미포함)"
        label variable v232 "성인학원교육"
        label variable v233 "기타교육"
        label variable v234 "11.음식·숙박"
        label variable v235 "식사비"
        label variable v236 "숙박비"
        label variable v237 "12.기타상품및서비스"
        label variable v238 "이미용서비스"
        label variable v239 "이미용기기"
        label variable v240 "위생및이미용용품"
        label variable v241 "시계및장신구"
        label variable v242 "기타개인용품"
        label variable v243 "사회복지"
        label variable v244 "보험"
        label variable v245 "기타금융"
        label variable v246 "기타서비스"
        label variable v247 "비소비지출"
        label variable v248 "경상조세"
        label variable v249 "비경상조세"
        label variable v250 "연금"
        label variable v251 "사회보장"
        label variable v252 "이자비용"
        label variable v253 "가구간이전지출"
        label variable v254 "비영리단체로이전"
        label variable v255 "기타지출"
        label variable v256 "자산변동으로 인한 지출"
        label variable v257 "부채감소를 위한 지출"
        label variable v258 "자산이전"
        label variable v259 "1 dong(urban) 도시구분여부"

